CREATE TABLE LANGUAGE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100)
);

CREATE TABLE TEACHER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    SALARY NUMBER,

    LANGUAGE_ID NUMBER,

    CONSTRAINT FK_TEACHER_LANGUAGE
        FOREIGN KEY (LANGUAGE_ID)
        REFERENCES LANGUAGE(ID)
);