CREATE TABLE DOCTOR (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    SALARY NUMBER
);

CREATE TABLE PATIENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    AGE NUMBER
);

CREATE TABLE DOCTOR_PATIENTS (
    DOCTOR_ID NUMBER,
    PATIENT_ID NUMBER,

    CONSTRAINT PK_DOCTOR_PATIENT
        PRIMARY KEY (DOCTOR_ID, PATIENT_ID),

    CONSTRAINT FK_DOCTOR_PATIENT_DOCTOR
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTOR(ID),

    CONSTRAINT FK_DOCTOR_PATIENT_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(ID)
);