CREATE TABLE EMPLOYEE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    AGE NUMBER
);

CREATE TABLE PHONE (
    ID NUMBER PRIMARY KEY,
    PHONE_NUMBER VARCHAR2(20),

    EMPLOYEE_ID NUMBER UNIQUE,

    CONSTRAINT FK_PHONE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(ID)
);