CREATE TABLE PLAYER (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) UNIQUE,
    AGE NUMBER,
CONSTRAINT PK_PLAYER_ID PRIMARY KEY(ID)

);

CREATE TABLE MANAGER (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100),
    SALARY NUMBER,

    CONSTRAINT UK_MANAGER_ID_NAME UNIQUE (ID, NAME)
);
SELECT *FROM MANAGER;

DROP TABLE MANAGER;
