CREATE TABLE HOSPITAL (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    NUMBEROFDOCTORS NUMBER,
    NUMBEROFPATIENT NUMBER
);


CREATE TABLE DOCTOR (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100),
    SALARY NUMBER,

    HOSPITAL_ID NUMBER,

    CONSTRAINT FK_DOCTOR_HOSPITAL
        FOREIGN KEY (HOSPITAL_ID)
        REFERENCES HOSPITAL(ID)
);


CREATE TABLE DOCTORDETAILS (
    ID NUMBER PRIMARY KEY,

    FULLADDRESS VARCHAR2(255),
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100),
    AGE NUMBER,

    CONSTRAINT FK_DOCTOR_DETAILS
        FOREIGN KEY (ID)
        REFERENCES DOCTOR(ID)
);


CREATE TABLE PATIENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    TYPEOFDISEASE VARCHAR2(255),

    DOCTOR_ID NUMBER,

    CONSTRAINT FK_PATIENT_DOCTOR
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTOR(ID)
);


CREATE TABLE HOSPITAL_PATIENT (

    HOSPITAL_ID NUMBER,
    PATIENT_ID NUMBER,

    PRIMARY KEY (HOSPITAL_ID, PATIENT_ID),

    CONSTRAINT FK_HP_HOSPITAL
        FOREIGN KEY (HOSPITAL_ID)
        REFERENCES HOSPITAL(ID),

    CONSTRAINT FK_HP_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(ID)
);