--CREAT MANAGER TABLE
CREATE TABLE "MANAGER"  (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50),
    age NUMBER,
    birthdate DATE,
    address VARCHAR2(200)
);

--DROPCOLUMN
ALTER TABLE MANAGER DROP COLUMN address;

--ADD COLUMN
ALTER TABLE MANAGER 
ADD (
City_Address varchar2(200) ,Street varchar2(200));

--RENAME COLUMN
ALTER TABLE MANAGER RENAME COLUMN name TO full_name;

--MANAGER IS READONLY
ALTER TABLE MANAGER READ ONLY;

--OWNER TABLE
CREATE TABLE owner AS SELECT id ,full_name,birthdate FROM manager WHERE 1=0; 

--RENAME
ALTER TABLE MANAGER RENAME TO MASTER;

--DROP ALL TABELS
DROP TABLE MASTER;
DROP TABLE OWNER;
